Lab3
saldaevvladimir/php-back pull request #4
Opened 2024-12-04 20:04 UTC by saldaevvladimir

- CRUD
- Forms

2025-02-01 06:36 UTC, praisethedeviI requested changes

2025-02-01 06:36 UTC, praisethedeviI commented on src/Kernel.php
> +class Kernel extends BaseKernel {
зачем?

2025-02-01 06:36 UTC, praisethedeviI commented on templates/project/_delete_form.html.twig
> +    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
твиг не входит в задачу

2025-02-01 06:36 UTC, praisethedeviI commented on docker/compose.yaml
>        POSTGRES_DB: symfony_db
Конфигурация докера в предыдущей задаче должна была делаться, не в этой

Или хотя бы сделать надо так, чтобы в этой лабе не было видно)

2025-02-01 06:36 UTC, praisethedeviI commented on src/Utils/Helpers.php
> +class Helpers {
Если хочется рандома, то есть FakerPHP)

2025-02-03 08:41 UTC, saldaevvladimir commented on src/Kernel.php
> +class Kernel extends BaseKernel {
> зачем?

форматер просто поменял

2025-02-03 08:42 UTC, saldaevvladimir commented on templates/project/_delete_form.html.twig
> +    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
> твиг не входит в задачу

можно оставить или обязательно нужно убрать твиги все?

2025-02-03 08:44 UTC, saldaevvladimir commented on src/Utils/Helpers.php
> +class Helpers {
> Если хочется рандома, то есть FakerPHP)

это не критично или нужно менять?)

2025-02-04 02:49 UTC, praisethedeviI commented on templates/project/_delete_form.html.twig
> +    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ project.id) }}">
Можно сохранить на отдельной ветке, что сделано, чтобы в 4ой задаче использовать. Из ветки этого PR'а избавляемся от твига

2025-02-04 02:50 UTC, praisethedeviI commented on src/Utils/Helpers.php
> +class Helpers {
некрит

2025-02-04 20:20 UTC, praisethedeviI approved these changes

2025-02-05 08:28 UTC, merged